import type { Article } from './types';

// Real-source display examples; never inserted as live automated news.
export const seedArticles: Article[] = [
  {
    title: '机鼻占了 38%：X-59 的设计为什么这么特别？',
    original_title: "The Plane That's 38% Nose",
    summary:
      'Real Engineering 的这期视频聚焦 X-59 的特殊工程设计。一个醒目的切入点是它极长的机鼻；关于构型的完整分析，需要回到原视频观看。',
    why_it_matters: '观察一个设计目标如何改变飞机的外形，并寻找其中的取舍。',
    category: '飞机设计',
    tags: ['X-59', '工程讲解', '飞机构型'],
    source_name: 'Real Engineering',
    original_url: 'https://www.youtube.com/watch?v=6B96xetwrqI',
    kind: 'video',
    featured: true,
    published_at: '2026-09-26T15:08:06+00:00',
    summary_basis: 'description',
    image_url: 'https://i.ytimg.com/vi/6B96xetwrqI/hqdefault.jpg',
    id: 'sample-1',
    status: 'published',
    quality_score: null,
    created_at: '2026-09-26T15:08:06+00:00',
  },
  {
    title: '给机翼“上色”，把气流留下的压力看出来',
    original_title: 'NASA Model Wing Lights Up During First Pressure Sensitive Paint Tests',
    summary:
      'NASA 兰利研究中心在风洞里使用非定常压力敏感涂料，研究模型周围的气流。来源摘录介绍了这项测试；具体方法与结果请阅读原文。',
    why_it_matters: '研究人员怎样把看不见的压力变化转化为可测量的信息？',
    category: '空气动力学',
    tags: ['风洞', '压力测量', '实验'],
    source_name: 'NASA Aeronautics',
    original_url:
      'https://www.nasa.gov/centers-and-facilities/langley/nasa-model-wing-lights-up-during-first-pressure-sensitive-paint-tests/',
    kind: 'article',
    featured: true,
    published_at: '2026-10-02T16:10:55+00:00',
    id: 'sample-2',
    status: 'published',
    quality_score: null,
    created_at: '2026-10-02T16:10:55+00:00',
    summary_basis: 'excerpt',
    image_url: null,
  },
  {
    title: '冰，为什么会改变一架飞机的飞行？',
    original_title: 'NASA Testing Aims at Supercooled Large Droplet Aviation Safety',
    summary:
      'NASA 正在改善测试设施，研究飞机遇到过冷大水滴时的结冰问题。这里关注的是一种航空研究课题，具体测试进展见来源原文。',
    why_it_matters: '机翼表面的细小变化，可能怎样影响气流与性能？',
    category: '空气动力学',
    tags: ['结冰', '航空研究'],
    source_name: 'NASA Aeronautics',
    original_url:
      'https://www.nasa.gov/image-article/nasa-testing-aims-at-supercooled-large-droplet-aviation-safety/',
    kind: 'article',
    featured: false,
    published_at: '2026-10-05T15:27:23+00:00',
    id: 'sample-3',
    status: 'published',
    quality_score: null,
    created_at: '2026-10-05T15:27:23+00:00',
    summary_basis: 'excerpt',
    image_url: null,
  },
  {
    title: '从突破音速开始：80 年飞行实验的好奇心',
    original_title: 'NASA Armstrong Celebrates 80 Years of Flight Innovation',
    summary:
      'NASA 阿姆斯特朗飞行研究中心回顾其飞行创新历程，包含早期超声速试验。它提供了一个认识实验飞行研究的入口。',
    why_it_matters: '一项新设计从纸面走向飞行验证，需要经历哪些实验？',
    category: '实验飞行器',
    tags: ['飞行试验', '航空历史'],
    source_name: 'NASA Aeronautics',
    original_url:
      'https://www.nasa.gov/news-release/nasa-armstrong-celebrates-80-years-of-flight-innovation/',
    kind: 'article',
    featured: false,
    published_at: '2026-09-28T19:20:01+00:00',
    id: 'sample-4',
    status: 'published',
    quality_score: null,
    created_at: '2026-09-28T19:20:01+00:00',
    summary_basis: 'excerpt',
    image_url: null,
  },
  {
    title: '把飞机设计，变成可以计算和优化的问题',
    original_title: 'peterdsharpe/AeroSandbox',
    summary:
      'AeroSandbox 是一个开源飞机设计与优化工具，涵盖空气动力、推进、结构和轨迹等分析。可从项目文档和示例了解这些工具怎样组合使用。',
    why_it_matters: '怎样把“感觉会更好”的设计，转化为可比较的参数与目标？',
    category: '开源工具',
    tags: ['Python', '设计优化', '开源'],
    source_name: 'GitHub',
    original_url: 'https://github.com/peterdsharpe/AeroSandbox',
    kind: 'project',
    featured: true,
    published_at: '2026-10-07T22:27:27Z',
    id: 'sample-5',
    status: 'published',
    quality_score: null,
    created_at: '2026-10-07T22:27:27Z',
    summary_basis: 'excerpt',
    image_url: null,
  },
  {
    title: '为自己的模拟器，接上一颗飞行动力学引擎',
    original_title: 'JSBSim-Team/jsbsim',
    summary:
      'JSBSim 是一个开源飞行动力学模型项目。可以从仓库的说明、模型文件和使用示例入手，探索模拟中的飞机运动怎样被描述。',
    why_it_matters: '游戏里的操作反馈，与飞行动力学模型之间怎样联系？',
    category: '模拟与游戏',
    tags: ['飞行模拟', '动力学', '开源'],
    source_name: 'GitHub',
    original_url: 'https://github.com/JSBSim-Team/jsbsim',
    kind: 'project',
    featured: false,
    published_at: '2026-10-06T08:52:14Z',
    id: 'sample-6',
    status: 'published',
    quality_score: null,
    created_at: '2026-10-06T08:52:14Z',
    summary_basis: 'excerpt',
    image_url: null,
  },
];
